# Generated by Django 5.1.6 on 2025-06-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='updated_at',
        ),
    ]
